#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

console.log('🚀 SnF Blog Frontend Setup');
console.log('==========================\n');

console.log('This script will help you configure your environment variables for the secure Strapi backend integration.\n');
console.log('🔒 SECURITY NOTE: These tokens will be stored server-side and are never exposed to the client browser.\n');

const questions = [
  {
    name: 'readToken',
    message: 'Enter your Strapi READ token: ',
    required: true
  },
  {
    name: 'writeToken',
    message: 'Enter your Strapi WRITE token: ',
    required: true
  }
];

const answers = {};

function askQuestion(index) {
  if (index >= questions.length) {
    createEnvFile();
    return;
  }

  const question = questions[index];
  rl.question(question.message, (answer) => {
    if (question.required && !answer.trim()) {
      console.log('❌ This field is required. Please try again.\n');
      askQuestion(index);
      return;
    }
    
    answers[question.name] = answer.trim();
    askQuestion(index + 1);
  });
}

function createEnvFile() {
  const envContent = `# Strapi API Configuration (Server-side only - tokens are secure)
# Generated by setup script
STRAPI_READ_TOKEN=${answers.readToken}
STRAPI_WRITE_TOKEN=${answers.writeToken}
`;

  const envPath = path.join(process.cwd(), '.env.local');
  
  try {
    fs.writeFileSync(envPath, envContent);
    console.log('\n✅ Environment file created successfully!');
    console.log(`📁 File location: ${envPath}`);
    console.log('\n🔒 Security Features:');
    console.log('   • Tokens are stored server-side only');
    console.log('   • No NEXT_PUBLIC_ prefix - tokens never exposed to client');
    console.log('   • All API calls go through secure server-side proxy');
    console.log('\n🎉 Setup complete! You can now run:');
    console.log('   npm run dev');
    console.log('   or');
    console.log('   yarn dev');
    console.log('   or');
    console.log('   pnpm dev');
  } catch (error) {
    console.error('\n❌ Error creating environment file:', error.message);
    console.log('\nPlease create a .env.local file manually with the following content:');
    console.log(envContent);
  }
  
  rl.close();
}

// Start the setup process
askQuestion(0); 